/*

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

const readline = require('readline');

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

rl.question('Enter a natural number ', (answer) => {

    const parsed = parseInt(answer);

    if (isNaN(parsed)) {
        console.log("Please, enter a natural number next time <3")
        return 0;
    }

    if (parsed < 2) {
        return 0;
    }

    let arr = [2];
    let f1 = 1;
    let f2 = 2;
    for (let f3 = 3; f3 < parsed; f3 = f1 + f2) {
        if (f3%2 === 0)
        {
            arr.push(f3);
        }
        f1 = f2;
        f2 = f3;
    }

    console.log("The sum of all even Fibonacci numbers bellow ", parsed, " is :", arr.reduce((accumulator, currentValue) => accumulator + currentValue));
    rl.close();
});