/*jshint esversion: 6 */
/*

Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate 
(polygonal) numbers and are generated by the following formulae:
Triangle 	  	P3,n=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Square 	  	    P4,n=n^2 	  	    1, 4, 9, 16, 25, ...
Pentagonal 	  	P5,n=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	P6,n=n(2n−1) 	  	1, 6, 15, 28, 45, ...
Heptagonal 	  	P7,n=n(5n−3)/2 	  	1, 7, 18, 34, 55, ...
Octagonal 	  	P8,n=n(3n−2) 	  	1, 8, 21, 40, 65, ...

The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.

1. The set is cyclic, in that the last two digits of each number is the first two digits 
of the next number (including the last number with the first).
2. Each polygonal type: triangle (P3,127=8128), square (P4,91=8281), and pentagonal (P5,44=2882), 
is represented by a different number in the set.
3. This is the only set of 4-digit numbers with this property.

Find the sum of the only ordered set of six cyclic 4-digit numbers 
for which each polygonal type: triangle, square, pentagonal, hexagonal, 
heptagonal, and octagonal, is represented by a different number in the set.

*/
const readline = require('readline');

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

rl.question('Press enter to continue : ', (answer) => {

    console.time("time");
    console.log("The sum of the only ordered set of six cyclic numbers of different polygonal type is   ", 
    FindCyclicalSet().reduce((a,b) => {return parseInt(a) + parseInt(b);}));
    console.log(console.timeEnd("time"));
    rl.close();
});

// FindCyclicalSet();
function FindCyclicalSet()
{
    let triangle = GenerateTriangleArray();
    let square = GenerateSquareArray();
    let pentagonal = GeneratePentagonalArray();
    let hexagonal = GenerateHexagonalArray();
    let heptagonal = GenerateHeptagonalArray();
    let octagonal = GenerateOctagonalArray();

    let cycle = SearchCycle(triangle, [square, pentagonal, hexagonal, heptagonal, octagonal]);

    return cycle;
}

function SearchCycle(startingPoint, otherArrays)
{
    let cycle = [];
    for (let nbr of startingPoint)
    {
        cycle.push(nbr);
        for(let i in otherArrays)
        {
            for (let comp of otherArrays[0])
            {
                if (nbr[2] + nbr[3] > comp[0] + comp[1])
                {
                    continue;
                }
                else if (nbr[2] + nbr[3] == comp[0] + comp[1])
                {
                    cycle.push(comp);
                    rest = [...otherArrays];
                    rest.shift();
                    _SearchCycle(comp, rest, cycle);
                    if (cycle.length == 6)
                    {
                        return cycle;
                    }
                }
                else
                {
                    otherArrays.push(otherArrays.shift());
                    break;
                }
            }
        }
        cycle.pop();
    }
}

function _SearchCycle(currentNumber, otherArrays, cycle)
{
    for(let i in otherArrays)
    {
        for (let comp of otherArrays[0])
        {
            if (currentNumber[2] + currentNumber[3] > comp[0] + comp[1])
            {
                continue;
            }
            else if (currentNumber[2] + currentNumber[3] == comp[0] + comp[1])
            {
                cycle.push(comp);
                rest = [...otherArrays];
                rest.shift();
                _SearchCycle(comp, rest, cycle);
                if (cycle.length == 6)
                {
                    return;
                }
            }
            else
            {
                otherArrays.push(otherArrays.shift());
                break;
            }
        }
    }
    if (cycle.length == 6 && cycle[0][0] + cycle[0][1] == cycle[5][2] + cycle[5][3])
    {
        return;
    }
    cycle.pop();
}


function GenerateTriangleArray()
{
    let n = 1;
    let nbr = 0;
    let arr = [];
    while(nbr < 10000)
    {       
        if (nbr > 999)
        {
            arr.push(nbr.toString());
        }
        nbr = (n*(n+1))/2;
        ++n;
    }
    return arr;
}

function GenerateSquareArray()
{
    let n = 1;
    let nbr = 0;
    let arr = [];
    while(nbr < 10000)
    {       
        if (nbr > 999)
        {
            arr.push(nbr.toString());
        }
        nbr = Math.pow(n,2);
        ++n;
    }
    return arr;
}

function GeneratePentagonalArray()
{
    let n = 1;
    let nbr = 0;
    let arr = [];
    while(nbr < 10000)
    {       
        if (nbr > 999)
        {
            arr.push(nbr.toString());
        }
        nbr = (n*(3*n-1))/2 ;
        ++n;
    }
    return arr;
}

function GenerateHexagonalArray()
{
    let n = 1;
    let nbr = 0;
    let arr = [];
    while(nbr < 10000)
    {       
        if (nbr > 999)
        {
            arr.push(nbr.toString());
        }
        nbr = n*(2*n-1);
        ++n;
    }
    return arr;
}

function GenerateHeptagonalArray()
{
    let n = 1;
    let nbr = 0;
    let arr = [];
    while(nbr < 10000)
    {       
        if (nbr > 999)
        {
            arr.push(nbr.toString());
        }
        nbr = (n*(5*n-3))/2;
        ++n;
    }
    return arr;
}

function GenerateOctagonalArray()
{
    let n = 1;
    let nbr = 0;
    let arr = [];
    while(nbr < 10000)
    {       
        if (nbr > 999)
        {
            arr.push(nbr.toString());
        }
        nbr = n*(3*n-2);
        ++n;
    }
    return arr;
}