/*jshint esversion: 6 */
/*

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	T_n=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	P_n=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	H_n=n(2n−1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T_285 = P_165 = H_143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

*/

/*
    It is easy to see that every hexagonal number is a triangular number.
    So we just need to check if an hexagonal number is pentagonal and call it a day.
*/

const readline = require('readline');

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

rl.question('Enter an integer : ', (answer) => {

    const parsed = parseInt(answer);

    if (isNaN(parsed)) {
        console.log("Please, enter a natural number next time <3");
        rl.close();
    } 
    else if (parsed < 1) {
        console.log("Enter a positive number next time");
        rl.close();
    } 
    else {
        let TriPenHex = [];
        let i = 1;
        while (TriPenHex.length < parsed)
        {
            let hex = HexagonalNumber(i);
            if (IsPentagonal(hex))
            {
                TriPenHex.push(hex);
            }
            i++;
        }
        console.log("The", parsed, " number(s) that is triangle, pentagonal and hexagonal is:", TriPenHex[TriPenHex.length - 1]);
        rl.close();
    }

});


function IsPentagonal(number)
{
    let value = (Math.sqrt(24*number + 1) + 1)/6;
    //console.log(value);
    return Number.isInteger(value);
}

function HexagonalNumber(number)
{
    return number*(2*number - 1);
}