/*jshint esversion: 6 */
/*

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	T_n=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	P_n=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	H_n=n(2n−1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T_285 = P_165 = H_143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

*/

const readline = require('readline');

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

rl.question('Enter an integer : ', (answer) => {

    const parsed = parseInt(answer);

    if (isNaN(parsed)) {
        console.log("Please, enter a natural number next time <3");
        rl.close();
    } 
    else if (parsed < 1) {
        console.log("Enter a positive number next time");
        rl.close();
    } 
    else {
        console.log("The", parsed, "-th number that is triangle, pentagonal and hexagonal is:", "ANSWER");
        rl.close();
    }

});