/*

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/
#include <stdio.h>

int main(){
    int f1 = 0;
    int f2 = 1;
    int total = 0;
    while (f2 < 4000000){
        int temp = f2;
        f2 += f1;
        f1 = temp;
        if (f2%2){}
        else
        {
                        total += f2;
        }
        
    }
    printf("The sum of the even terms in the Fibonacci sequence whose values do not exceep four million is %i.\n", total);
    return 0;
}