/*

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

function p002 (n) {
  console.time('p002')
  const answer = FibonacciSum(n)
  const time = console.timeEnd('p002')

  return { answer: answer, time: time }
}

function FibonacciSum (upperbound) {
  let f1 = 1n; let f2 = 2n
  let sum = 2n
  for (let f3 = 3n; f3 < BigInt(upperbound); f3 = f1 + f2) {
    if (f3 % 2n === 0n) {
      sum += f3
    }

    [f1, f2] = [f2, f3]
  }

  return sum.toString()
}

module.exports = p002
