const { performance } = require('perf_hooks')
/*

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

*/

/*

    To have K divisor, the number must be greater than K.
    I need a great bound or else, the computation may take forever

*/

/*
    Optimisation needed, brute force is SLOW
*/

function p012 (n) {
  const t0 = performance.now()
  let factors = 0
  let triangular = 0
  let natural = 1
  const primes = EratosthenesSieve(10 ** 6)

  while (factors <= n) {
    triangular += natural++
    factors = Factorise(triangular, primes)
  }

  const t1 = performance.now()
  return { answer: triangular, time: t1 - t0 }
}

function Factorise (number, primes) {
  const factorNumber = []
  let index = 0
  if (primes.indexOf(number) > 0) {
    return 1
  }
  for (const prime of primes) {
    while (number % prime === 0) {
      number /= prime
      factorNumber[index] !== undefined ? ++factorNumber[index] : factorNumber[index] = 2
      if (number % prime !== 0) {
        ++index
      }
    }
    if (number === 1) {
      return Object.values(factorNumber).reduce((acc, val) => { return acc * val }, 1)
    }
  }
}

function EratosthenesSieve (upperbound) {
  // We reduce the sieve in half by skipping every even number
  const oddUpperbound = Math.floor((upperbound + 1) / 2)
  const innerLimit = Math.floor((Math.floor(Math.sqrt(upperbound)) - 1) / 2)
  const numberArr = Array(oddUpperbound).fill(true)
  const primes = [2]
  numberArr[0] = false
  for (let i = 1; i <= innerLimit; ++i) {
    if (numberArr[i]) {
      for (let j = 2 * i * (i + 1); j <= oddUpperbound; j += 2 * i + 1) {
        numberArr[j] = false
      }
    }
  }

  for (const i in numberArr) {
    if (numberArr[i]) {
      primes.push(2 * i + 1)
    }
  }

  return primes
}

module.exports = p012
